### ISSUE TITLE
Favicon setting creates orphan file or incorrect file

### ISSUE THREAD

**Issue by wilhelmer** [squidfunk/mkdocs-material#1282]
__I checked that...__

- [x] ... the documentation does not mention anything about my problem
- [x] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... there are no open or closed issues that are related to my problem

## Description

1. If you specifiy a custom favicon via the `favicon` setting, Material still generates the default `favicon.png` file ![favicon](https://user-images.githubusercontent.com/2234833/65968736-e9fbcf80-e463-11e9-93b0-dde3aeb49227.png) and puts it in `assets/images/`. 
The generated help correctly uses the custom favicon, but an orphan `favicon.png` file is included in the output.
2. If you specify a custom favicon via the `favicon` setting and the path to the custom icon is `[docs_dir]/assets/images/favicon.png`, the custom icon is **not** included in the output. Instead, the default icon ![favicon](https://user-images.githubusercontent.com/2234833/65968736-e9fbcf80-e463-11e9-93b0-dde3aeb49227.png) is used.

### Expected behavior

The correct favicon should be displayed in the output. No orphan `favicon.png` file should be included in the output.

### Actual behavior

See description.

### Steps to reproduce the bug

1. Create an empty project. 
2. In `mkdocs.yml`, set the `favicon` setting to any path (causes issue 1) or to `assets/images/favicon.png` (causes issue 2).

### Package versions

* Python: `3.7.3.`
* MkDocs: `1.0.4`
* Material: `4.4.2`

### Project configuration

Issue 1: 

``` yaml
theme:
  name: material
  favicon: favicon.ico
```

Issue 2: 

``` yaml
theme:
  name: material
  favicon: assets/images/favicon.png
```

### System information

* OS: Windows 10
* Browser: Any

**Comment by squidfunk** [comment]
First of all: thanks for being the first one using the new issue template! I really hope that the quality of issues improves, as there were lots of issues where I had to ask a lot of questions to drill down to the real problem. Big up!

I investigated your problem and these are my findings:

__Regarding 1.__

This is true. When running `mkdocs build` there are also other files inside the `site` directory that either are not actively used (e.g. `images/icons/*.svg` files, as they are inlined in the template during the build) or _might_ not be used (e.g. `fonts/*`). All these files are build artifacts, like the favicon, and I assume that MkDocs is putting them there because they are all contained within the theme folder, respectively `material`. We cannot do anything about this within the scope of this project, as this is a feature by MkDocs which makes total sense, as all assets should be included. You could, however, delete them with a simple post-processing script.

__Regarding 2.__

If the path exactly matches a path of a file in the theme, then (again) I assume, that MkDocs will favor the theme file over the custom file. I don't know whether this might be a MkDocs bug, might be, but it's again not fixable by this project.

**Comment by wilhelmer** [comment]
Thanks for investigating. 

1. I ran a tool to find unused files in the output (i.e., files that aren't referenced in any file in site_dir), and `favicon.png` is the **only** file that isn't actively used. I also don't have `images/icons/*.svg` in my output dir. I understand that this may not be fixable in the template, just want to point out it doesn't seem to be a general issue, at least not in my project.

2. Okay. Maybe you should add to the documentation that the default path can't be used for custom icons.

**Comment by squidfunk** [comment]
> Okay. Maybe you should add to the documentation that the default path can't be used for custom icons.

This actually sounds like an error in MkDocs to me. Otherwise, if it is intended behavior we could add a short notice to the customization guide.

@waylan could you comment whether this is intended behavior by MkDocs or should we open an issue? To sum up: the problem is that assets that are provided by the theme seem to be override assets that are provided by the user when `mkdocs build` is run. The user probably does not know what paths are "reserved" by assets provided by the theme, resulting in unexpected behavior.

**Comment by waylan** [comment]
I expect this is the bug in MkDocs which was fixed in mkdocs/mkdocs#1672 and will be available in the next release.

**Comment by squidfunk** [comment]
@waylan awesome, thanks! As it's confirmed to be a bug in MkDocs, I assume this issue can be closed?

**Comment by wilhelmer** [comment]
Hmm. I installed the latest dev version via `pip install https://github.com/mkdocs/mkdocs/archive/master.tar.gz`, but both issues persist. Which is a little weird since @neoword did the same (as mentioned in https://github.com/mkdocs/mkdocs/pull/1672) and it worked for him. Or do I specifically have to work off commit #f200a60? How do I do that?

But yeah, I suppose this issue can be closed anyway. Thanks for your time!

**Comment by waylan** [comment]
MkDocs itself does not look at the theme specific settings. Those are only taken into account in the templates provided by the theme, and theme templates have no control over which files are written and which are not. Therefore, if I understand what the Material theme is doing correctly,  you have two possible scenarios:

1. You add a custom favicon image at the theme's default location of your `docs_dir`. In this case, with the fix in mkdocs/mkdocs#1672, your image file will replace/overwrite the default image file (prior to the fix, the theme's default image file would overwrite your custom image file). Presumably, you would not need to set anything in your config file in this scenario.

2. You use a custom location (set in your config file) and add a favicon image at that location of your `docs_dir`. In this case, the theme's default image would be written to the default location, but be unused, and the custom image would exist at the custom location and be used. There is no way to the theme to prevent the default image file from being written. Also, this behavior should be the same regardless of the change in mkdocs/mkdocs#1672.

Given the above, my recommendation to theme authors is to not have a setting for a custom favicon location. The favicon should always be overridable at its default location (using scenario 1). Of course, until the fix in mkdocs/mkdocs#1672 lands, the custom location setting provides a workaround. And people are entitled to have their own opinions and want custom locations, so if a third party theme offers that, we don't prevent it. 

@wilhelmer, its not clear to me which scenario you are having trouble with. If scenario 1, then the current working tree of the `master` branch should work find for you. If scenario 2, then there should be no difference between the dev code and the latest release.

**Comment by wilhelmer** [comment]
@waylan Scenario 1 doesn't get fixed for me with the latest `master` branch version.

Steps to reproduce:
1. Create empty project.
2. Create `assets/images` and put a custom `favicon.png` file in it. 
3. Use the following minimal `mkdocs.yml`:
``` yml
site_name: My Docs
theme:
  name: material
```
3.  Make sure mkdocs-material is installed and that `mkdocs --version` shows `mkdocs, version 1.1.dev0`
4. Build.

Result: `site_dir/assets/images/favicon.png` contains the template favicon, not the custom favicon.

**Comment by squidfunk** [comment]
@wilhelmer all user-supplied files must be in the `docs` folder, so it should be `docs/assets/...`

**Comment by wilhelmer** [comment]
Yes sorry, I did that, just documented it incorrectly. Fixed.

**Comment by waylan** [comment]
I just tested this and cannot replicate the reported problem with the current `master` branch of MkDocs. I created a new project with a minimal `mkdocs.yml` file:

```yml
site_name: My Docs
theme:
    name: material
```

I built the site and at `site/assets/images/favicon.png` I found Material's default image as expected.

Then I added an custom image at `docs/assets/images/favicon.png` and built a second time. I then found my custom image at `site/assets/images/favicon.png`.

> Result: `site_dir/assets/images/favicon.png` contains the template favicon, not the custom favicon.

Note that you should be looking at `site/...` not `site_dir/...` here. Perhaps you have some remnants from an old build?

**Comment by waylan** [comment]
I should note that while the custom image is correctly writing to the `site_dir` (note the path in the address bar) ...

![Screen Shot 2019-10-03 at 8 36 42 PM](https://user-images.githubusercontent.com/78846/66173440-3ee34580-e61e-11e9-97bd-5e473e8a4d4e.png)

... the image is not used anywhere on the site or in the browser tab as I expected.

![Screen Shot 2019-10-03 at 8 38 24 PM](https://user-images.githubusercontent.com/78846/66173477-528eac00-e61e-11e9-97bd-3617ea8d8ae5.png)

However, those are issues for the theme. I am not seeing any issue with MkDocs itself.

**Comment by squidfunk** [comment]
@waylan thanks for testing. The MkDocs default favicon is displayed which already indicates the problem - you need to clear your browser cache. Browsers can be a little bitchy when updating a favicon.

**Comment by wilhelmer** [comment]
Ok here's the thing: It works on Unix (Mac), but not on Windows. Windows handles path names differently, so I suppose the issue must be caused by that.

I had a similar issue in mkdocs-exclude, see here: https://github.com/apenwarr/mkdocs-exclude/issues/2

**Comment by neoword** [comment]
@wilhelmer says:

> Hmm. I installed the latest dev version via `pip install https://github.com/mkdocs/mkdocs/archive/master.tar.gz`, but both issues persist. Which is a little weird since @neoword did the same (as mentioned in [mkdocs/mkdocs#1672](https://github.com/mkdocs/mkdocs/pull/1672)) and it worked for him. Or do I specifically have to work off commit #f200a60? How do I do that?
> 
> But yeah, I suppose this issue can be closed anyway. Thanks for your time!

and...@wilhelmer says:
> Ok here's the thing: It works on Unix (Mac), but not on Windows. Windows handles path names differently, so I suppose the issue must be caused by that.

FWIW... yes I'm on a Mac. Did not try on Windows. Windows `C:\` backslashes strikes again! :\ :\
Glad that mystery is solved.

**Comment by waylan** [comment]
@wilhelmer could you please create a new issue in the MkDocs project with a full summary of the problem (minimal reproducible example). Be sure to include any system specific information. If you can reproduce the problem with the default `mkdocs` theme, that would be even better (if you can't include that as well). Feel free to link to both this issue and mkdocs/mkdocs#1672. 

I'm certain that this is not an issue specific to Material and we are creating a lot of noise for @squidfunk.
