### ISSUE TITLE
Version 6.2.1 breaks mkdocs build

### ISSUE THREAD

**Issue by PascalBrouwers** [squidfunk/mkdocs-material#2145]
- [x] I've read the [contribution guidelines][1] and agree with them

__I've found a bug and checked that ...__

- [ ] ... the problem doesn't occur with the default MkDocs template
- [x] ... the problem is not in any of my customizations (CSS, JS, template)
- [x] ... the documentation does not mention anything about my problem
- [x] ... there are no open or closed issues that are related to my problem

### Steps to reproduce the bug

1. pip install mkdocs

### Package versions

* Python: 2.7.17
* MkDocs: 1.1.2
* Material: 6.2.1

### Project configuration

``` yaml
The contents of your mkdocs.yml
theme: material
```

### System information

  [1]: https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md

**Comment by squidfunk** [comment]
6.2.0 indeed broke the build. 6.2.1 should work as expected, as the errors have been fixed.

**Comment by squidfunk** [comment]
I just tested 6.2.1 again:

```
$ virtualenv venv
created virtual environment CPython3.8.3.final.0-64 in 563ms
  creator CPython3Posix(dest=/Users/squidfunk/Desktop/mkdocs-test-2/venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/squidfunk/Library/Application Support/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . ./venv/bin/activate
$ pip install mkdocs-material     
Collecting mkdocs-material
  Downloading mkdocs_material-6.2.1-py2.py3-none-any.whl (4.0 MB)
     |████████████████████████████████| 4.0 MB 1.5 MB/s 
Collecting mkdocs-material-extensions>=1.0
  Using cached mkdocs_material_extensions-1.0.1-py3-none-any.whl (8.0 kB)
Collecting mkdocs>=1.1
  Using cached mkdocs-1.1.2-py3-none-any.whl (6.4 MB)
Collecting pymdown-extensions>=7.0
  Using cached pymdown_extensions-8.0.1-py2.py3-none-any.whl (206 kB)
Collecting Pygments>=2.4
  Using cached Pygments-2.7.3-py3-none-any.whl (950 kB)
Collecting markdown<3.3,>=3.2
  Using cached Markdown-3.2.2-py3-none-any.whl (88 kB)
Processing /Users/squidfunk/Library/Caches/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c/PyYAML-5.3.1-cp38-cp38-macosx_10_15_x86_64.whl
Processing /Users/squidfunk/Library/Caches/pip/wheels/48/d7/34/372e0521bd5c9f6dcdff307e37ef6f9c00c1e1e2afc9707b5c/livereload-2.6.3-py2.py3-none-any.whl
Collecting tornado>=5.0
  Using cached tornado-6.1-cp38-cp38-macosx_10_9_x86_64.whl (416 kB)
Collecting lunr[languages]==0.5.8
  Using cached lunr-0.5.8-py2.py3-none-any.whl (2.3 MB)
Collecting click>=3.3
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting Jinja2>=2.10.1
  Using cached Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Processing /Users/squidfunk/Library/Caches/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4/future-0.18.2-py3-none-any.whl
Processing /Users/squidfunk/Library/Caches/pip/wheels/ff/d5/7b/f1fb4e1e1603b2f01c2424dd60fbcc50c12ef918bafc44b155/nltk-3.5-py3-none-any.whl
Collecting MarkupSafe>=0.23
  Using cached MarkupSafe-1.1.1-cp38-cp38-macosx_10_9_x86_64.whl (16 kB)
Collecting joblib
  Using cached joblib-1.0.0-py3-none-any.whl (302 kB)
Collecting tqdm
  Using cached tqdm-4.54.1-py2.py3-none-any.whl (69 kB)
Collecting regex
  Using cached regex-2020.11.13-cp38-cp38-macosx_10_9_x86_64.whl (284 kB)
Installing collected packages: mkdocs-material-extensions, markdown, PyYAML, tornado, six, livereload, future, joblib, click, tqdm, regex, nltk, lunr, MarkupSafe, Jinja2, mkdocs, pymdown-extensions, Pygments, mkdocs-material
Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 Pygments-2.7.3 click-7.1.2 future-0.18.2 joblib-1.0.0 livereload-2.6.3 lunr-0.5.8 markdown-3.2.2 mkdocs-1.1.2 mkdocs-material-6.2.1 mkdocs-material-extensions-1.0.1 nltk-3.5 pymdown-extensions-8.0.1 regex-2020.11.13 six-1.15.0 tornado-6.1 tqdm-4.54.1
WARNING: You are using pip version 20.2.4; however, version 20.3.3 is available.
You should consider upgrading via the '/Users/squidfunk/Desktop/mkdocs-test-2/venv/bin/python -m pip install --upgrade pip' command.
$ mkdocs new .                 
INFO    -  Writing config file: ./mkdocs.yml 
INFO    -  Writing initial docs: ./docs/index.md 
# ... add material theme to MkDocs ...
$ mkdocs serve                 
INFO    -  Building documentation... 
INFO    -  Cleaning site directory 
INFO    -  Documentation built in 0.21 seconds 
[I 201222 13:43:46 server:335] Serving on http://127.0.0.1:8000
INFO    -  Serving on http://127.0.0.1:8000
[I 201222 13:43:46 handlers:62] Start watching changes
INFO    -  Start watching changes
[I 201222 13:43:46 handlers:64] Start detecting changes
INFO    -  Start detecting changes
[I 201222 13:43:48 handlers:135] Browser Connected: http://localhost:8000/
INFO    -  Browser Connected: http://localhost:8000/
^C[I 201222 13:43:50 server:358] Shutting down...
INFO    -  Shutting down...
$ mkdocs build
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /Users/squidfunk/Desktop/mkdocs-test-2/site 
INFO    -  Documentation built in 0.21 seconds 
```

Works perfectly. Thus, your error is related to errors in 6.2.0 which have been fixed in 6.2.1. Closing.

**Comment by PascalBrouwers** [comment]
Oh, was still busy editing this issue. I'll just put a comment then.
```
13:11:16       01 pip3 install mkdocs
13:11:18       01 Collecting mkdocs
13:11:18       01   Using cached https://files.pythonhosted.org/packages/5d/89/ed04b217404bbba031c4e2e084f36ef840b8663fce0b80302b547e651e4d/mkdocs-1.1.2-py3-none-any.whl
13:11:18       01 Collecting Jinja2>=2.10.1 (from mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
13:11:18       01 Collecting Markdown>=3.2.1 (from mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/ac/ef/24a91ca96efa0d7802dffb83ccc7a3c677027bea19ec3c9ee80be740408e/Markdown-3.3.3-py3-none-any.whl
13:11:18       01 Collecting livereload>=2.5.1 (from mkdocs)
13:11:18       01 Collecting PyYAML>=3.10 (from mkdocs)
13:11:18       01 Collecting tornado>=5.0 (from mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/01/d1/8750ad20cbcefb499bb8b405e243f83c2c89f78d139e6f8c8d800640f554/tornado-6.1-cp36-cp36m-manylinux1_x86_64.whl
13:11:18       01 Collecting click>=3.3 (from mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
13:11:18       01 Collecting lunr[languages]==0.5.8 (from mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/15/a4/3043c019613a1d60abb6e150b7665761bdd236a0d915d447d21c4415fddd/lunr-0.5.8-py2.py3-none-any.whl
13:11:18       01 Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
13:11:18       01 Collecting importlib-metadata; python_version < "3.8" (from Markdown>=3.2.1->mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/7a/85/ac225e35048e050a6351b6f1251cdb2b6060092f2c6840aff1d6319941b1/importlib_metadata-3.3.0-py3-none-any.whl
13:11:18       01 Collecting six (from livereload>=2.5.1->mkdocs)
13:11:18       01   Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
13:11:18       01 Collecting future>=0.16.0 (from lunr[languages]==0.5.8->mkdocs)
13:11:19       01 Collecting nltk>=3.2.5; python_version > "2.7" and extra == "languages" (from lunr[languages]==0.5.8->mkdocs)
13:11:19       01 Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->Markdown>=3.2.1->mkdocs)
13:11:19       01   Using cached https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
13:11:19       01 Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->Markdown>=3.2.1->mkdocs)
13:11:19       01   Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
13:11:19       01 Collecting regex (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs)
13:11:19       01   Using cached https://files.pythonhosted.org/packages/5a/75/aca08032c9752a75acc60ff7f4e58f1a74164b996395f44727ffdb17ebaf/regex-2020.11.13-cp36-cp36m-manylinux1_x86_64.whl
13:11:19       01 Collecting joblib (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs)
13:11:19       01   Using cached https://files.pythonhosted.org/packages/34/5b/bd0f0fb5564183884d8e35b81d06d7ec06a20d1a0c8b4c407f1554691dce/joblib-1.0.0-py3-none-any.whl
13:11:19       01 Collecting tqdm (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs)
13:11:19       01   Using cached https://files.pythonhosted.org/packages/8a/54/115f0c28a61d56674c3a5e05c46d6c3523ad196e1dcd3e2d8b119026df36/tqdm-4.54.1-py2.py3-none-any.whl
13:11:19       01 Installing collected packages: MarkupSafe, Jinja2, zipp, typing-extensions, importlib-metadata, Markdown, six, tornado, livereload, PyYAML, click, future, regex, joblib, tqdm, nltk, lunr, mkdocs
13:11:22       01 Successfully installed Jinja2-2.11.2 Markdown-3.3.3 MarkupSafe-1.1.1 PyYAML-5.3.1 click-7.1.2 future-0.18.2 importlib-metadata-3.3.0 joblib-1.0.0 livereload-2.6.3 lunr-0.5.8 mkdocs-1.1.2 nltk-3.5 regex-2020.11.13 six-1.15.0 tornado-6.1 tqdm-4.54.1 typing-extensions-3.7.4.3 zipp-3.4.0
13:11:22     ✔ 01 user@0.0.0.0 5.327s
13:11:22       02 pip3 install mkdocs-material
13:11:23       02 Collecting mkdocs-material
13:11:24       02   Downloading https://files.pythonhosted.org/packages/3c/37/9825742a84d7f450677b626c2c1071deeabe6eee9622b68191134bd85c76/mkdocs_material-6.2.1-py2.py3-none-any.whl (4.0MB)
13:11:25       02 Collecting markdown<3.3,>=3.2 (from mkdocs-material)
13:11:25       02   Downloading https://files.pythonhosted.org/packages/a4/63/eaec2bd025ab48c754b55e8819af0f6a69e2b1e187611dd40cbbe101ee7f/Markdown-3.2.2-py3-none-any.whl (88kB)
13:11:25       02 Collecting mkdocs>=1.1 (from mkdocs-material)
13:11:25       02   Using cached https://files.pythonhosted.org/packages/5d/89/ed04b217404bbba031c4e2e084f36ef840b8663fce0b80302b547e651e4d/mkdocs-1.1.2-py3-none-any.whl
13:11:25       02 Collecting Pygments>=2.4 (from mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/85/c5/c437c383d5917fae9782eb6588bec8aff931afe13c76b9e8c03dacee9beb/Pygments-2.7.3-py3-none-any.whl
13:11:26       02 Collecting pymdown-extensions>=7.0 (from mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/08/a1/087c5f2028098ae16526080f185fa437912624ab5f89f02a138b0b9857be/pymdown_extensions-8.0.1-py2.py3-none-any.whl
13:11:26       02 Collecting mkdocs-material-extensions>=1.0 (from mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/52/1c/d44c75a584e19a6b63d20befe6ac282a8cc092bf1299dd3b225fd3c3e239/mkdocs_material_extensions-1.0.1-py3-none-any.whl
13:11:26       02 Collecting importlib-metadata; python_version < "3.8" (from markdown<3.3,>=3.2->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/7a/85/ac225e35048e050a6351b6f1251cdb2b6060092f2c6840aff1d6319941b1/importlib_metadata-3.3.0-py3-none-any.whl
13:11:26       02 Collecting livereload>=2.5.1 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02 Collecting tornado>=5.0 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/01/d1/8750ad20cbcefb499bb8b405e243f83c2c89f78d139e6f8c8d800640f554/tornado-6.1-cp36-cp36m-manylinux1_x86_64.whl
13:11:26       02 Collecting lunr[languages]==0.5.8 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/15/a4/3043c019613a1d60abb6e150b7665761bdd236a0d915d447d21c4415fddd/lunr-0.5.8-py2.py3-none-any.whl
13:11:26       02 Collecting click>=3.3 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
13:11:26       02 Collecting PyYAML>=3.10 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02 Collecting Jinja2>=2.10.1 (from mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/30/9e/f663a2aa66a09d838042ae1a2c5659828bb9b41ea3a6efa20a20fd92b121/Jinja2-2.11.2-py2.py3-none-any.whl
13:11:26       02 Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata; python_version < "3.8"->markdown<3.3,>=3.2->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
13:11:26       02 Collecting zipp>=0.5 (from importlib-metadata; python_version < "3.8"->markdown<3.3,>=3.2->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/41/ad/6a4f1a124b325618a7fb758b885b68ff7b058eec47d9220a12ab38d90b1f/zipp-3.4.0-py3-none-any.whl
13:11:26       02 Collecting six (from livereload>=2.5.1->mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
13:11:26       02 Collecting future>=0.16.0 (from lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material)
13:11:26       02 Collecting nltk>=3.2.5; python_version > "2.7" and extra == "languages" (from lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material)
13:11:26       02 Collecting MarkupSafe>=0.23 (from Jinja2>=2.10.1->mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/b2/5f/23e0023be6bb885d00ffbefad2942bc51a620328ee910f64abe5a8d18dd1/MarkupSafe-1.1.1-cp36-cp36m-manylinux1_x86_64.whl
13:11:26       02 Collecting joblib (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material)
13:11:26       02   Using cached https://files.pythonhosted.org/packages/34/5b/bd0f0fb5564183884d8e35b81d06d7ec06a20d1a0c8b4c407f1554691dce/joblib-1.0.0-py3-none-any.whl
13:11:26       02 Collecting tqdm (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material)
13:11:27       02   Using cached https://files.pythonhosted.org/packages/8a/54/115f0c28a61d56674c3a5e05c46d6c3523ad196e1dcd3e2d8b119026df36/tqdm-4.54.1-py2.py3-none-any.whl
13:11:27       02 Collecting regex (from nltk>=3.2.5; python_version > "2.7" and extra == "languages"->lunr[languages]==0.5.8->mkdocs>=1.1->mkdocs-material)
13:11:27       02   Using cached https://files.pythonhosted.org/packages/5a/75/aca08032c9752a75acc60ff7f4e58f1a74164b996395f44727ffdb17ebaf/regex-2020.11.13-cp36-cp36m-manylinux1_x86_64.whl
13:11:27       02 Installing collected packages: typing-extensions, zipp, importlib-metadata, markdown, tornado, six, livereload, future, joblib, tqdm, regex, click, nltk, lunr, PyYAML, MarkupSafe, Jinja2, mkdocs, Pygments, pymdown-extensions, mkdocs-material-extensions, mkdocs-material
13:11:32       02 Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 PyYAML-5.3.1 Pygments-2.7.3 click-7.1.2 future-0.18.2 importlib-metadata-3.3.0 joblib-1.0.0 livereload-2.6.3 lunr-0.5.8 markdown-3.3.3 mkdocs-1.1.2 mkdocs-material-6.2.1 mkdocs-material-extensions-1.0.1 nltk-3.5 pymdown-extensions-8.0.1 regex-2020.11.13 six-1.15.0 tornado-6.1 tqdm-4.54.1 typing-extensions-3.7.4.3 zipp-3.4.0
13:11:32     ✔ 02 user@0.0.0.0 10.226s
13:11:32       03 cd '/home/user/deployment/releases/20201222120316'/docs && mkdocs build
13:11:33       03 Traceback (most recent call last):
13:11:33       03   File "/home/user/.local/bin/mkdocs", line 11, in <module>
13:11:33       03     sys.exit(cli())
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
13:11:33       03     return self.main(*args, **kwargs)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
13:11:33       03     rv = self.invoke(ctx)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
13:11:33       03     return _process_result(sub_ctx.command.invoke(sub_ctx))
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
13:11:33       03     return ctx.invoke(self.callback, **ctx.params)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
13:11:33       03     return callback(*args, **kwargs)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/__main__.py", line 152, in build_command
13:11:33       03     build.build(config.load_config(**kwargs), dirty=not clean)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/config/base.py", line 197, in load_config
13:11:33       03     errors, warnings = cfg.validate()
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/config/base.py", line 115, in validate
13:11:33       03     post_failed, post_warnings = self._post_validate()
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/config/base.py", line 95, in _post_validate
13:11:33       03     config_option.post_validation(self, key_name=key)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/config/config_options.py", line 469, in post_validation
13:11:33       03     config[key_name] = theme.Theme(**theme_config)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/theme.py", line 45, in __init__
13:11:33       03     self._load_theme_config(name)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/theme.py", line 75, in _load_theme_config
13:11:33       03     theme_dir = utils.get_theme_dir(name)
13:11:33       03   File "/home/user/.local/lib/python3.6/site-packages/mkdocs/utils/__init__.py", line 297, in get_theme_dir
13:11:33       03     return os.path.dirname(os.path.abspath(theme.load().__file__))
13:11:33       03   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2460, in load
13:11:33       03     self.require(*args, **kwargs)
13:11:33       03   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2483, in require
13:11:33       03     items = working_set.resolve(reqs, env, installer, extras=self.extras)
13:11:33       03   File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 790, in resolve
13:11:33       03     raise VersionConflict(dist, req).with_context(dependent_req)
13:11:33       03 pkg_resources.VersionConflict: (Markdown 3.3.3 (/home/user/.local/lib/python3.6/site-packages), Requirement.parse('markdown<3.3,>=3.2'))
```

Still not working with 6.2.1

**Comment by PascalBrouwers** [comment]
@squidfunk reopen please

**Comment by squidfunk** [comment]
Please, the next time, first complete the issue template and then submit it. The Markdown version was pinned due to some issues with the new HTML parser which was introduced in 3.2. I'm still in the process of opening an issue over at Python Markdown.

**Comment by squidfunk** [comment]
The Markdown version range has been lifted in 6.2.2.
