### ISSUE TITLE
The codeblock copy button and comments are not shown

### ISSUE THREAD

**Issue by ehguille** [squidfunk/mkdocs-material#3420]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

The codeblock copy button and comments are not shown.

### Expected behaviour

There should be an icon to copy the codeblock and the comments should be shown as popups

### Actual behaviour

The icon is missing and the comments don't render as popups

### Steps to reproduce

mkdocs serve (or build).

![image](https://user-images.githubusercontent.com/55703981/148045733-fee3880d-c25c-4f94-97bf-2b6a7378263e.png)

Sorry I can't copy the code.

![image](https://user-images.githubusercontent.com/55703981/148046063-e155bf56-386b-4279-9a68-dfae2b73de27.png)

### Package versions

Python 3.10.0
mkdocs, version 1.2.3
Version: 8.1.4+insiders.4.5.1

### Configuration

```yaml
site_name: Programación

theme:
  name: material
  logo: assets/imgs/logo-programacion.png
  favicon: assets/imgs/logo-programacion.png
#  custom_dir: overrides
  font: false
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: java
    accent: indigo
  language: es
  features:
    - content.code.annotate
    - search.suggest
    - navigation.instant
    - search.highlight
    - header.autohide
    - navigation.tabs 
    - navigation.indexes
    - navigation.tracking
    - announce.dismiss
   
#extra_javascript:
#  - https://kit.fontawesome.com/8c2d521aaf.js
  
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      type: datetime  

extra:
  generator: false
   consent:
    title: Consentimiento de cookies
    description: > 

      Esta página usa cookies para ver qué apartados resultan más interesantes a los usuarios y así poder ser mejorada. Puedes gestionar el acceso a estas cookies en el siguiente botón.
      
#extra_css:
#    - 'assets/stylesheets/extra.css'

markdown_extensions: 
    - meta
    - attr_list
    - abbr
    - admonition
    - pymdownx.caret
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.smartsymbols
    - pymdownx.tilde
    - pymdownx.inlinehilite
    - pymdownx.mark
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.extra
    - pymdownx.magiclink
    - pymdownx.progressbar
    - pymdownx.tasklist
    - pymdownx.tabbed
    - pymdownx.critic
    - markdown.extensions.footnotes
    - markdown.extensions.tables
    - pymdownx.snippets
    - def_list
    - lightgallery
    - toc:
       toc_depth: 5
    - smarty:
       smart_angled_quotes: true
       smart_dashes: false
    - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.betterem:
       smart_enable: true
    - pymdownx.tasklist:
       custom_checkbox: true
```

### System information

Windows 10 21H2
Firefox and Chrome at least

**Comment by squidfunk** [comment]
Thanks for reporting. Please provide a _minimal_ example with Markdown. I'm not able to reproduce it.

**Comment by ehguille** [comment]
Sure.

[ejercicios-propuestos.md](https://guille.es/ejercicios-propuestos.md)

![image](https://user-images.githubusercontent.com/55703981/148061452-2134bc3d-a70e-406f-a8ab-d681f181db69.png)

**Comment by squidfunk** [comment]
Is there an error shown in the console of your browser?

**Comment by ehguille** [comment]
Yes:

bundle.21ccbe1b.min.js:3 Uncaught ReferenceError: Missing element: expected ".md-typeset > :first-child" to be present
    at W (bundle.21ccbe1b.min.js:3)
    at wa (bundle.21ccbe1b.min.js:3)
    at bundle.21ccbe1b.min.js:3
    at e._subscribe (bundle.21ccbe1b.min.js:3)
    at e._trySubscribe (bundle.21ccbe1b.min.js:3)
    at bundle.21ccbe1b.min.js:3
    at Xe (bundle.21ccbe1b.min.js:3)
    at e.subscribe (bundle.21ccbe1b.min.js:3)
    at v (bundle.21ccbe1b.min.js:3)
    at h (bundle.21ccbe1b.min.js:3)

**Comment by squidfunk** [comment]
Thanks for the report. I think I now know where this is coming from. You have enabled the `announce.dismiss` feature flag, but there's no announcement bar which caused an expected element not to be present, leading to the error. I just pushed a fix in [`cad59ac`](https://github.com/squidfunk/mkdocs-material-insiders/commit/cad59acd678e5f18b12180349cd10194f50df71c), which should resolve the issues you reported.

**Comment by ehguille** [comment]
Hi again!

I've just updated and still not working. However, commented the     - announce.dismiss line in yml file and works fine.

The error in console:

```
bundle.21ccbe1b.min.js:3 Uncaught ReferenceError: Missing element: expected ".md-typeset > :first-child" to be present
    at W (bundle.21ccbe1b.min.js:3)
    at wa (bundle.21ccbe1b.min.js:3)
    at bundle.21ccbe1b.min.js:3
    at e._subscribe (bundle.21ccbe1b.min.js:3)
    at e._trySubscribe (bundle.21ccbe1b.min.js:3)
    at bundle.21ccbe1b.min.js:3
    at Xe (bundle.21ccbe1b.min.js:3)
    at e.subscribe (bundle.21ccbe1b.min.js:3)
    at v (bundle.21ccbe1b.min.js:3)
    at h (bundle.21ccbe1b.min.js:3)
```

The update log:

- [ ] PS C:\Users\guillermo> pip install --upgrade git+https://**@github.com/squidfunk/mkdocs-material-insiders.git
- [ ] Collecting git+https://****@github.com/squidfunk/mkdocs-material-insiders.git
- [ ]   Cloning https://****@github.com/squidfunk/mkdocs-material-insiders.git to c:\users\guillermo\appdata\local\temp\pip-req-build-jo9reo7c
- [ ]   Running command git clone --filter=blob:none -q 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' 'C:\Users\guillermo\AppData\Local\Temp\pip-req-build-jo9reo7c'
- [ ]   warning: redirecting to https://github.com/squidfunk/mkdocs-material-insiders.git/
- [ ]   Resolved https://****@github.com/squidfunk/mkdocs-material-insiders.git to commit 7a40c3446c72c7a316c280daf4c46f018461d96c
- [ ]   Preparing metadata (setup.py) ... done
- [ ] Requirement already satisfied: jinja2>=2.11.1 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (3.0.3)
- [ ] Requirement already satisfied: markdown>=3.2 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (3.3.6)
- [ ] Requirement already satisfied: mkdocs>=1.2.3 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (1.2.3)
- [ ] Requirement already satisfied: mkdocs-material-extensions>=1.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (1.0.3)
- [ ] Requirement already satisfied: pygments>=2.10 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (2.11.1)
- [ ] Requirement already satisfied: pymdown-extensions>=9.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (9.1)
- [ ] Requirement already satisfied: cairosvg>=2.5 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (2.5.2)
- [ ] Requirement already satisfied: pillow>=8.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (9.0.0)
- [ ] Requirement already satisfied: requests>=2.26 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs-material==8.1.4+insiders.4.5.1) (2.27.0)
- [ ] Requirement already satisfied: tinycss2 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (1.1.1)
- [ ] Requirement already satisfied: cssselect2 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (0.4.1)
- [ ] Requirement already satisfied: defusedxml in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (0.7.1)
- [ ] Requirement already satisfied: cairocffi in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (1.3.0)
- [ ] Requirement already satisfied: MarkupSafe>=2.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from jinja2>=2.11.1->mkdocs-material==8.1.4+insiders.4.5.1) (2.0.1)
- [ ] Requirement already satisfied: watchdog>=2.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (2.1.6)
- [ ] Requirement already satisfied: ghp-import>=1.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (2.0.2)
- [ ] Requirement already satisfied: mergedeep>=1.3.4 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (1.3.4)
- [ ] Requirement already satisfied: PyYAML>=3.10 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (6.0)
- [ ] Requirement already satisfied: importlib-metadata>=3.10 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (4.10.0)
- [ ] Requirement already satisfied: packaging>=20.5 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (21.3)
- [ ] Requirement already satisfied: pyyaml-env-tag>=0.1 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (0.1)
- [ ] Requirement already satisfied: click>=3.3 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (8.0.3)
- [ ] Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->mkdocs-material==8.1.4+insiders.4.5.1) (2.0.9)
- [ ] Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->mkdocs-material==8.1.4+insiders.4.5.1) (1.26.7)
- [ ] Requirement already satisfied: idna<4,>=2.5 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->mkdocs-material==8.1.4+insiders.4.5.1) (3.3)
- [ ] Requirement already satisfied: certifi>=2017.4.17 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from requests>=2.26->mkdocs-material==8.1.4+insiders.4.5.1) (2021.10.8)
- [ ] Requirement already satisfied: colorama in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from click>=3.3->mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (0.4.4)
- [ ] Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from ghp-import>=1.0->mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (2.8.2)
- [ ] Requirement already satisfied: zipp>=0.5 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from importlib-metadata>=3.10->mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (3.7.0)
- [ ] Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from packaging>=20.5->mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (3.0.6)
- [ ] Requirement already satisfied: cffi>=1.1.0 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cairocffi->cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (1.15.0)
- [ ] Requirement already satisfied: webencodings in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cssselect2->cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (0.5.1)
- [ ] Requirement already satisfied: pycparser in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from cffi>=1.1.0->cairocffi->cairosvg>=2.5->mkdocs-material==8.1.4+insiders.4.5.1) (2.21)
- [ ] Requirement already satisfied: six>=1.5 in c:\users\guillermo\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->ghp-import>=1.0->mkdocs>=1.2.3->mkdocs-material==8.1.4+insiders.4.5.1) (1.16.0)

**Comment by squidfunk** [comment]
The commit is correct, it's the HEAD of the `master` branch. However, it seems that the changes are not picked up. Maybe try a clean installation by uninstalling it and reinstalling. The fix is definitely in `master` and works.

**Comment by ehguille** [comment]
Great.

I just love the way you work 👍🏽 .
