### ISSUE TITLE
[insider] blog post plugin breaks with custom `nav` key

### ISSUE THREAD

**Issue by vwxyzjn** [squidfunk/mkdocs-material#4348]
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/squidfunk/mkdocs-material/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... the problem doesn't occur with the `mkdocs` or `readthedocs` themes
- [X] ... the problem persists when all overrides are removed, i.e. `custom_dir`, `extra_javascript` and `extra_css`
- [X] ... the documentation does not mention anything about my problem
- [X] ... there are no open or closed issues that are related to my problem

### Description

```
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - index.md
```
works but not 

```
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - Overview: index.md
```

### Expected behaviour

Should work without error

### Actual behaviour

```
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - Overview: index.md
```

produces
```
(cleanrl-py3.9) ➜  test3 git:(jax-ppo-envpool-atari) ✗ mkdocs serve
INFO     -  Building documentation...
INFO     -  Cleaning site directory
Traceback (most recent call last):
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 282, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/material/plugins/blog/plugin.py", line 272, in on_files
    root.append({ name: data })
```

### Steps to reproduce

Follow tutorial at https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/ and then use 

```
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - Overview: index.md
```
as the `mkdocs.yml`

### Package versions

N/A. Using the latest fix from https://github.com/squidfunk/mkdocs-material/issues/4345

### Configuration

```yaml
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog:
      blog_dir: . 
  - search
  - tags
nav:
  - Overview: index.md
```

### System information

n/a

**Comment by squidfunk** [comment]
Thanks for reporting! Fixed in squidfunk/mkdocs-material-insiders@f92137cab33284ad09c10e8dc4940c7f5e2d304b.

**Comment by squidfunk** [comment]
Released as part of 8.4.4-insiders-4.23.2.

**Comment by vwxyzjn** [comment]
This problem persists in the latest commit (c70dcb54465092f7f527a04385c79597e990133e)

```
Collecting git+https://****@github.com/squidfunk/mkdocs-material-insiders.git
  Cloning https://****@github.com/squidfunk/mkdocs-material-insiders.git to /tmp/pip-req-build-gs5_ou61
  Running command git clone --filter=blob:none --quiet 'https://****@github.com/squidfunk/mkdocs-material-insiders.git' /tmp/pip-req-build-gs5_ou61
  Resolved https://****@github.com/squidfunk/mkdocs-material-insiders.git to commit c70dcb54465092f7f527a04385c79597e990133e
  Preparing metadata (setup.py) ... done
(cleanrl-py3.9) ➜  test3 git:(jax-ppo-envpool-atari) ✗ mkdocs serve                 
INFO     -  Building documentation...
INFO     -  Cleaning site directory
Traceback (most recent call last):
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/__main__.py", line 181, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 63, in serve
    config = builder()
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/serve.py", line 58, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/commands/build.py", line 282, in build
    files = config['plugins'].run_event('files', files, config=config)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/mkdocs/plugins.py", line 102, in run_event
    result = method(item, **kwargs)
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/material/plugins/blog/plugin.py", line 271, in on_files
    root.append({ name: data })
AttributeError: 'NoneType' object has no attribute 'append'
```

but if i do `pip install --upgrade git+https://xxxx@github.com/squidfunk/mkdocs-material-insiders.git@f92137cab33284ad09c10e8dc4940c7f5e2d304b` then the issue was fixed

**Comment by vwxyzjn** [comment]
It also gives me the same error if I use the default file structure like

```
  File "/home/costa/.cache/pypoetry/virtualenvs/cleanrl-ghSZGHE3-py3.9/lib/python3.9/site-packages/material/plugins/blog/plugin.py", line 272, in on_files
    root.append({ name: data })
AttributeError: 'NoneType' object has no attribute 'append'
(cleanrl-py3.9) ➜  test3 git:(jax-ppo-envpool-atari) ✗ tree
.
├── docs
│   ├── blog
│   │   ├── index.md
│   │   └── posts
│   │       └── hello_world.md
│   ├── dummy.md
│   └── index.md
└── mkdocs.yml
```

```
site_name: My Blog
theme:
  name: material
plugins:
  - meta
  - blog
      # blog_dir: . 
  - search
  - tags
nav:
  - Overview: index.md
```

**Comment by squidfunk** [comment]
Thanks for reporting. That is very weird, as other users reported this problem is fixed now. Please provide a self-contained reproduction and attach it here as a zip. Also, please specify what system you're using (Windows? You didn't specify it in the original issue, but it's highly relevant).

**Comment by squidfunk** [comment]
Okay, I can reproduce it – it's a configuration error: the blog must be contained in a _section_, not a separate entry:

This doesn't work:

``` yaml
nav:
  - Overview: index.md
```

This works:

``` yaml
nav:
  - Overview:
    - index.md
```

Note that your directory layout is also wrong. You#re telling the plugin that the blog lives in `.`, but your `docs_dir` says that it lives in `blog`:

This is wrong:

```
.
├── docs
│   ├── blog
│   │   ├── index.md
│   │   └── posts
│   │       └── hello_world.md
│   ├── dummy.md
│   └── index.md
└── mkdocs.yml
```

This should work:

```
.
├── docs
│   ├── posts
│   │    └── hello_world.md
│   ├── dummy.md
│   └── index.md
└── mkdocs.yml
```

I'm closing the issue, but I'll check if we can improve error reporting next time I work on the plugin.

**Comment by squidfunk** [comment]
@vwxyzjn there was indeed another bug, that was fixed in squidfunk/mkdocs-material-insiders@27caebdab.
