### ISSUE TITLE
Embedding external file doesn't work since 9.1.13

### ISSUE THREAD

**Issue by doricci** [squidfunk/mkdocs-material#5556]
### Bug description

Starting from the version 9.1.13, building the MKDocs documentation doesn't work and crash when trying to embed an external java file.

Exception logs:

```logs
WARNING  -  Config value 'dev_addr': The use of the IP address '0.0.0.0' suggests a production environment or the use of a proxy to connect to the MkDocs server. However, the MkDocs' server is intended for local development purposes only. Please use a third party production-ready server instead.
INFO     -  Building documentation...
INFO     -  Cleaning site directory
ERROR    -  Error reading page 'index.md': Snippet at path '../files/ExampleDataSourceConfiguration.java' could not be found
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 234, in serve_command
    serve.serve(dev_addr=dev_addr, livereload=livereload, watch=watch, **kwargs)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 83, in serve
    builder(config)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 76, in builder
    build(config, live_server=live_server, dirty=dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 308, in build
    _populate_page(file.page, config, files, dirty)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/build.py", line 181, in _populate_page
    page.render(config, files)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/structure/pages.py", line 270, in render
    self.content = md.convert(self.markdown)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/markdown/core.py", line 261, in convert
    self.lines = prep.run(self.lines)
                 ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymdownx/snippets.py", line 364, in run
    return self.parse_snippets(lines)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pymdownx/snippets.py", line 349, in parse_snippets
    raise SnippetMissingError("Snippet at path '{}' could not be found".format(path))
pymdownx.snippets.SnippetMissingError: Snippet at path '../files/ExampleDataSourceConfiguration.java' could not be found
```

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)

### Reproduction

[embedding_java_file.zip](https://github.com/squidfunk/mkdocs-material/files/11552497/embedding_java_file.zip)

### Steps to reproduce

1. Unzip the file _embedding_java_file.zip_
3. execute the command next to the mkdocs.yaml: 
   ```bash
    docker run --name mkdocs --rm \
         --env LOCAL_MKDOCS=/docs/mkdocs.yml \
         --rm -p 8000:8000 \
         -v $PWD:/docs \
         squidfunk/mkdocs-material:9.1.13
   ```
⇾ it should fail with the logs from the previous section
if you change with the version 9.1.12 it works perfectly fine

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Related to a [bug in Snippets](https://github.com/facelessuser/pymdown-extensions/releases/tag/10.0.1), an upstream dependency. The bug was fixed in a subsequent version. If you update to the 9.1.14 container, the issue is gone. Related:

- https://github.com/squidfunk/mkdocs-material/discussions/5529

**Comment by doricci** [comment]
Same for us, ths issue is still present... even when updating the version of _pymdown-extensions_ to 10.0.1 like mentionned in the link that @squidfunk published

Here is the list of all dependency version installed in our pipeline via _pip list_ :
```text 
Package                    Version
-------------------------- ---------
certifi                    2023.5.7
charset-normalizer         3.1.0
click                      8.1.3
colorama                   0.4.6
distlib                    0.3.6
filelock                   3.10.7
ghp-import                 2.1.0
idna                       3.4
Jinja2                     3.1.2
Markdown                   3.3.7
MarkupSafe                 2.1.2
mergedeep                  1.3.4
mkdocs                     1.4.3
mkdocs-material            9.1.14
mkdocs-material-extensions 1.1.1
packaging                  23.1
pip                        23.0.1
pipenv                     2023.3.20
platformdirs               3.2.0
Pygments                   2.15.1
pymdown-extensions         10.0.1
python-dateutil            2.8.2
PyYAML                     6.0
pyyaml_env_tag             0.1
regex                      2023.5.5
requests                   2.31.0
setuptools                 67.6.1
six                        1.16.0
urllib3                    2.0.2
virtualenv                 20.21.0
virtualenv-clone           0.5.7
watchdog                   3.0.0
wheel                      0.40.0
[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
```

**Comment by squidfunk** [comment]
Reopening. cc @facelessuser – is that related?

**Comment by facelessuser** [comment]
10.0.0 is not necessarily backward compatible. The change was made to give safer defaults, especially if someone was careless enough to enable Snippets on a live server that parsers dynamic user-generated Markdown on the front end. 

10.0.1 fixes a regression, but that does not mean everything will be exactly as it was in the 9.x.x releases.

You will either need to follow the instructions to update your paths to work with the new change, or you can disable the `restrict_base_path` option to get legacy results. This is all stated clearly in the changelog as @squidfunk has pointed out. Any issues or questions related to the change should be taken upstream to my repo.

**Comment by doricci** [comment]
Thank you for the answer!

Indeed, the `restrict_base_path` option fixed our issues, I just saw that by default the snippets needs to be a child folder of the `base_path`.

It's fixed for us, thank you for the help :)
