### ISSUE TITLE
Blurry fonts on Windows – Help wanted 👋

### ISSUE THREAD

**Issue by stojan97** [squidfunk/mkdocs-material#6396]
### Context

**Operating System:** Windows 10
**Font:** Segoe UI
**Static Site Generator 1:** Docusaurus
**Static Site Generator 2:** Material Mkdocs (or any mkdocs theme)
**Browser:** Google Chrome, Microsoft Edge (so far I tested only on these browsers)

### Bug description

I'm coming from Docusaurus and trying to switch to Material Mkdocs for my docs and notes, but the fonts and overall rendering of the text looked a bit **blurry**.

I went into analyzing and inspect the fonts into more detail, and it seems that for any web page from Material Mkdocs, the SSG uses **grayscale rendering** as opposed to **subpixel rendering (when you zoom in you will see colored edges on the font)**.

I checked other Static site generators, and they all seem fine and render it fine, but Mkdocs always renders them a bit blurry.

When I went to inspect the fonts side by side, the difference became clear.

And this does not happen for some fonts, it's the same thing for **any font** in Mkdocs, **LaTeX** as well.

For those who think `font-smooth` or `text-rendering` can do something, try it yourself, they don't change anything.

### Related links

- **Subpixel rendering** - [Docusaurus]( https://docusaurus.io/docs#fast-track), [VuePress](https://vuepress.vuejs.org/guide/getting-started.html)
- **Grayscale Rendering** - [Material Mkdocs](https://squidfunk.github.io/mkdocs-material/getting-started/), [Mkdocs](https://www.mkdocs.org/getting-started/)

### Reproduction

You can reproduce it by checking either of the sites that I mentioned above and see it for yourself after zooming in the fonts.

![font-smoothing](https://github.com/squidfunk/mkdocs-material/assets/10180981/0cd80ddb-7fcb-44e8-9a7e-13883f0c9462)

### Steps to reproduce

1. Go to either of the sites that I mentioned above
2. Take a screenshot of some of the text
3. Compare them side by side in any image editing tool (Paint 3D for me)

### Browser

Chrome, Edge

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. So this is likely almost a relic of 2016, where `text-rendering` was not available, and we've kept it since then, but I'M happy to re-evaluate. Would you like to contribute a PR for this? I'm pretty sure only these lines need to be changed, but one should search the code base and check:

https://github.com/squidfunk/mkdocs-material/blob/fd90fa6518f06debc1312b167ae3e94386937dff/src/templates/assets/stylesheets/main/_typeset.scss#L29-L30

**Comment by stojan97** [comment]
Hey @squidfunk, to me it does not look like an issue with the properties but something in the core of mkdocs not related to this theme.

Since it happens also on the official mkdocs web pages.

Moreover, I tried experimenting with the properties in the browser by adding `text-rendering`, removing `webkit-font-smoothing` , `-moz-osx-font-smoothing`, play around with the values, but nothing changes, the rendering is still the same.

**Comment by squidfunk** [comment]
Then it may be related to different fonts. Have you tried [switching the font](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/#regular-font) in Material for MkDocs to `Segoe UI`? Are you using the exact same settings? Without a minimal reproduction or knowing exactly what you#re doing, we're unable to help you.

**Comment by squidfunk** [comment]
By the way, Docusaurus seems to use the exact same settings. I don't have Windows at my disposal, so it's pretty hard for me to debug this. In any case, help appreciated.

**Comment by stojan97** [comment]
**As I mentioned in the description**, I already tried with multiple fonts (`Roboto` and `Segoe UI`), also tried on multiple different browsers (Chrome and MS Edge).

I can spin a VM to reproduce it on a Ubuntu OS and see whether it happens there but the reproduction is pretty trivial.

I mentioned that the problem is not in the CSS properties because I already tried using exactly the same properties between Docusaurus and Material Mkdocs and the problem still persisted for any font, and I don't need to test it locally, because it happens for any webpage using Material Mkdocs theme (tried  [Official Material Mkdocs](https://squidfunk.github.io/mkdocs-material/getting-started/), [Some other website using Material Mkdocs](https://cp-algorithms.com/)).

I'm not sure what steps should I provide to support this more because it happens for any website using Material Mkdocs and it's pretty trivial to verify it against some other that does not have this problem.

I'm curious what is the rendering side-by-side between Material Mkdocs and Docusaurus on your OS?

**Comment by alexvoss** [comment]
Here are bits from a Material for MkDocs site (above) that uses Cantarell like the Docusaurus website (below). This is using Firefox under Debian Bookworm; image is a screenshot from the composite of two screenshots zoomed to 400% in Gimp.

![image](https://github.com/squidfunk/mkdocs-material/assets/4134224/b8be0db4-1ce9-42d3-bbc1-da3dc312514c)

It might be worth testing this using a different web browser under Windows. Edge is based on Chromium, so not sure if testing with Edge and Chrome will even yield different rendering results? How about Firefox?

It seems to me that Windows is the OS that has the widest range of parameters that influence what things look like. Various settings plus display drivers might play a role. Chrome itself has a [Cleartype Text Tuner](https://www.guidingtech.com/top-ways-to-fix-google-chrome-blurry-font-rendering-on-windows/) built in as well? Quite a few options to iterate through if we wanted to pin this problem down.

**Comment by stojan97** [comment]
I saw from a bunch of articles and forums that Chrome and Microsoft rendering issues have been solved long long ago.

And to me, it doesn't make sense to think of  OS or Browser problems because if it was, it should happen for any website, but in this case, only Material Mkdocs produces such grayscsle rendering. 

Btw the examples you shared are using grayscale rendering. 

To differentiate, you can observe that subpixel rendering has colored edges.

**Comment by alexvoss** [comment]
> Btw the examples you shared are using grayscale rendering.

So they are. Sorry, I am not that au-fait with anti-aliasing technologies. 

I managed to get sub-pixel rendering in Firefox on Debian via a setting in Gnome Tweaks. Now, I still get grayscale rendering on my Material test site but sub-pixel rendering on the Docusaurus page. 

There is one difference I noted, which is that Docusaurus does not load the fonts from Google Fonts. Rather, it specifies a long list of fonts to try and the Cantarell font used comes from the system. [Turning off Google Fonts](https://squidfunk.github.io/mkdocs-material/setup/changing-the-fonts/?h=autoloading#autoloading) in the Material site and tweaking `--md-text-font-family` got me a system font but no sub-pixel rendering, despite setting `text-rendering` to match what Docusaurus does:

```css
html {
  text-rendering: optimizelegibility;
}

body {
  --md-text-font-family: Cantarell,Helvetica,Arial,sans-serif;
}
```

Hope this helps in some way.

**Comment by stojan97** [comment]
Yeah, I basically went through the same journey as I mentioned above, I tried all the   CSS properties, played around with them, and tried a couple of different fonts sources, as well disable the Google fonts with `font: false` in the YAML.

A couple of observations that I noticed:

* LaTeX (MathJAX / KaTeX) fonts are also grayscale rendered on Material, on most of the other sites they are not

* JetBrains Mono font in codeblocks uses subpixel on Material

* Also tried with `system-ui`, same problem was happening

It leads me to think that it might happen on some fonts, but I'm not 100% convinced until I try text font in codeblocks or vice-versa.

If it happens for some fonts and not for others, we probably should investigate the font sources more thoroughly.

### Wild guess

Maybe there is something in the `Mkdocs` core, as I mentioned above, which might alter the rendering since exactly the same problems happen even on the official Mkdocs theme for me. (Probably, I'm looking at it in this way because I'm a newbie about how Mkdocs is working)

### Things to try

* Create a simple HTML document and test it locally and see what's the default rendering

* Add the same font sources as Docusaurus and retest

**Comment by alexvoss** [comment]
As far as I understand things (still need to make that caveat), MkDocs itself has little to do with the production of the HTML, much less the styling of the results. The HTML is generated via [Python Markdown](https://pypi.org/project/Markdown/). I can see the logic that you argue this must have to do with MkDocs itself if it happens with different themes but this might be a commonality simply between the CSS used in the two themes. The OS and browser will have an influence as they ultimately determine how fonts get rendered. CSS settings are merely a declaration of a web designer's wishes.

I had a look on a Mac and I did not see subpixel rendering on any page I tried, with Firefox and with Safari. This is on a retina display as well as an external full-HD monitor. It seems that Apple dropped this since MacOS Mojave.

**Comment by stojan97** [comment]
I understand that OS and Browsers can alter the rendering of the fonts but I would expect consistency across all webpages if that was the case.

- I also tried setting `JetBrains Mono` font as a text but it was still using grayscale rendering.

## Dummy HTML document

I created a simple HTML document with nothing but the font and see how is the default in the Browser.
![image](https://github.com/squidfunk/mkdocs-material/assets/10180981/e18cddf9-3839-455a-a840-92fedd5e94d2)
![image](https://github.com/squidfunk/mkdocs-material/assets/10180981/687fb4cf-bc65-47d7-988c-392de3725b7b)

<br>

The font was rendered with `subpixel rendering` so I'm inclined to say that it's something about Mkdocs that messes up the rendering.

Here is comparison side by side:
![dummy_html](https://github.com/squidfunk/mkdocs-material/assets/10180981/fff0a4a9-f3dd-43c1-9206-bcaad0f16fd9)

## Font Source

I don't think that the problem is in the font sources because for Math Equations I tried KaTeX local CSS and fonts, and I'm using exactly the same for Docusaurus, so exactly the same font is loaded, and can be seen in the Chrome Devtools, but still Material renders it using grayscale.

## Possible causes

### Python Markdown

I checked [Python Markdown ](https://pypi.org/project/Markdown/), but it is unlikely that Python Markdown is causing the problem since it only converts markdown to simple HTML.

### Scaling of the Webpage
This can be something in the CSS rules defined, I also saw that something is wrong in the conversion of the `font-size` in rem, it is specified that it is `16px` but when I inspect it or put manually `16px` as font size, it looks very different.
![image](https://github.com/squidfunk/mkdocs-material/assets/10180981/498467bc-f487-4b0d-8f4d-d3d8eff900c5)

I'm not sure why do we need [CSS resets](https://github.com/squidfunk/mkdocs-material/blob/master/src/templates/assets/stylesheets/main/_resets.scss), since that thing was long ago, and no website follows that practice nowadays.

### REM values

I'm not sure but I'm thinking whether this issue has something to do with the REM values used for the `font-size` and how it is calculated with the `px2rem` function.

I also noticed the official Mkdocs theme also uses `rem` values for font size but I couldn't fix it when changing them to `px`.

### OBSERVATION: Background color to white changes the rendering of the normal text but not Latex equations

When I changed the `background-color` to `white`, even though it was written as inherited in the Chrome Devtools, when I re-set it, the rendering changed to subpixel for all text that are under the div `md-typeset`.

Not sure whether this will give us some hint into the problem but I guess someone with more knowhow of the CSS styles of this repo can come in and guide us where to look further given the above findings.

**Comment by squidfunk** [comment]
Thanks for putting in the time to do all the research to all of you. To be honest, I'm a bit lost here, and since I don't have a Windows machine at my disposal, I'm of no help here. If you use the issue tracker search, you'll find several comments where I explain why we use `rem` values and that we're not intending to change that for several reasons.

If we can improve the situation in a way where we don't need to change the entire code base from `rem` to `px`, I'm happy to consider for inclusion into `master`, but as I said, I need to rely on third-party contributions here. However, introducing additional workarounds for browser bugs, please understand that we need to keep the theme maintainable and usable for the majority of users, so we can only do that to a limited extent.

**Comment by squidfunk** [comment]
I experimented on a non-retina monitor on macOS and see differences experimenting with `-webkit-font-smoothing`:

![Bildschirm­foto 2023-11-29 um 10 17 45](https://github.com/squidfunk/mkdocs-material/assets/932156/fb79c939-00ed-40a9-830e-7e78b6bec2e4)

It also affects the rendering of MathJax formulas. Personally, I like `antialiased` better because is easier to read, at least on macOS on Retina and non-Retina screens, but it might be different on other systems. Docusaurus uses `antialiased` like we do, but they also define `text-rendering: optimizelegibility`. As you said in https://github.com/squidfunk/mkdocs-material/issues/6396#issuecomment-1827742194 you already added it without effect, so I have no idea where this is coming from.

**Comment by HonkingGoose** [comment]
I checked Can I Use, which is a site that explains if certain features have good browser support. Here are the links:

- [Can I Use `font-smooth`](https://caniuse.com/font-smooth)
- [Can I Use `text-rendering`](https://caniuse.com/mdn-css_properties_text-rendering)

Maybe there are combinations of browsers and operating systems that don't play well with some font rendering techniques?

**Comment by stojan97** [comment]
The font rendering CSS properties are only supported by macOS systems, which is specified in the docs on most of the up-to-date references.

**Comment by stojan97** [comment]
After playing around with the styling I found that that removing the sidebars (left and right) are fixing the problem so this could be some problem with margins...

The font is crystal clear after removing them.
![sidebars](https://github.com/squidfunk/mkdocs-material/assets/10180981/4d2dcbce-aadb-47ee-a185-29a6a28de256)

**Comment by stojan97** [comment]
Does anyone know how the 2 sidebars and the 3 lines drawer could be affecting the size of the main content or the font itself?

**Comment by squidfunk** [comment]
So if removing the two sidebars fixes, I'm pretty sure this is a paint/layout containment problem that is very browser specific. In fact, it's a leaky abstraction and, IMHO, should be considered a browser bug. It might be possible to use [CSS containment](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_containment) to workaround the issue, but I'm not sure.

**Comment by squidfunk** [comment]
Another candidate that might influence the rendering:

https://github.com/squidfunk/mkdocs-material/blob/d0a536acc2322a1afd007280a04db96731ec26d1/src/templates/assets/stylesheets/main/components/_sidebar.scss#L126-L127

Could you try removing that property and see if it improves the situation?

**Comment by stojan97** [comment]
Hey @squidfunk, I found two ways, experimenting with `contain` property did not work, also `backface-visibility` did not do anything but maybe the following workarounds would spark some insights.

## Approach 1 (EASY APPROACH) adding z-index: -1 to md-content div

simply setting 

```css
.md-content {
    z-index: -1;
}
```
Fixes the font rendering.

## Approach 2 (HARDER WAY)

This one requires to alter `md-skip` and `md-sidebar` to work

1. Unsetting either property from `md-skip` container:
 - `position: fixed`
 - `z-index: -1`

2. Unsetting `position: sticky` from `md-sidebar`

**Comment by squidfunk** [comment]
Thanks for investigating! Note that setting `z-index: -1` will make the elements unselectable, so it's not really an option. Try clicking on a content tab – it doesn't work anymore. Also unsetting `position: sticky` and the other things you suggest are major changes to the mechanics of the theme that we cannot put into `master`.

**Comment by stojan97** [comment]
Yeah, links are not working inside the main content, so any ideas what the above observations could suggest?

**Comment by squidfunk** [comment]
I think the browser moves the layers containing the text to the GPU. I'm not sure why this is happening. There's probably a way to fix this but I'm not seeing it yet.

**Comment by stojan97** [comment]
`position: unset` on `md-skip` and `md-content` fixes it, but you know the sidebars will be ruined.

**Comment by squidfunk** [comment]
I'm closing this as unfixable for now, but if you or somebody else makes progress, we can definitely add this to `master` if it keeps all existing functionality.
