### ISSUE TITLE
Markdown formatted mermaid nodes do not follow text color of dark theme

### ISSUE THREAD

**Issue by schneekluth** [squidfunk/mkdocs-material#6700]
### Bug description

When formatting a mermaid node [using markdown](https://mermaid.js.org/syntax/flowchart.html#markdown-formatting) the text color is not inherited from dark theme. The node is rendered unreadable.

![example](https://github.com/squidfunk/mkdocs-material/assets/5740913/29eaaba3-5b95-4a6f-b20b-e2df07010f41)

### Related links

- [Diagrams](https://squidfunk.github.io/mkdocs-material/reference/diagrams/)
- [Mermaid Docs on Markdown Formatting](https://mermaid.js.org/syntax/flowchart.html#markdown-formatting)

### Reproduction

[9.5.5-mermaid-vs.zip](https://github.com/squidfunk/mkdocs-material/files/14072072/9.5.5-mermaid-vs.zip)

### Steps to reproduce

1. Minimal Reproduction Example contains a Markdown formatted mermaid node
2. Turn on dark theme

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting and providing the excellent reproduction! This made fixing the problem straight forward. Fixed in 335dd3add, which sets the text color for Markdown-formatted nodes.

**Comment by squidfunk** [comment]
Released as part of [9.5.6](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.6).

**Comment by bennert** [comment]
I tested [9.5.6](https://squidfunk.github.io/mkdocs-material/changelog/#9.5.6), Most of it looks fine, but I noticed that for "pie", "quadrantChart", "gantt" and "journey" the text color is still not inherited from dark theme

**Comment by squidfunk** [comment]
Well, I was only to able to verify the data that was given to us in the minimal reproduction. If you discover more cases, please provide a complete minimal reproduction so we can solve all of them. Please create a new issue for this.
