### ISSUE TITLE
Some math equations cannot be rendered correctly  

### ISSUE THREAD

**Issue by fadni** [squidfunk/mkdocs-material#6852]
### Bug description

I have enabled Katex library according to the documentation in [https://squidfunk.github.io/mkdocs-material/reference/math/](https://squidfunk.github.io/mkdocs-material/reference/math/). Some equations are displayed quite fine. However, formulas inside `\begin{cases}` and `\end(cases)` within `$$` block are not displayed correctly unless i have to add empty line after/before `SS`
For example, in the following text, the equation won't be rendered correctly
```
For what value $a$ is the function $f$ given by
$$
f(t) = 
\begin{cases}
    \frac{\sqrt{4+t^2} - 2}{t^2} & t=0 \\
    a & t \neq 0
\end{cases}
$$
continuous everywhere?
```
But, if I make blank spaces, i.e.,
```
For what value $a$ is the function $f$ given by

$$
f(t) = 
\begin{cases}
    \frac{\sqrt{4+t^2} - 2}{t^2} & t=0 \\
    a & t \neq 0
\end{cases}
$$

continuous everywhere?
```
then it will be rendered correctly

### Related links

- [Reporting a bug](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/)
-

### Reproduction

[mkdocs.zip](https://github.com/squidfunk/mkdocs-material/files/14445306/mkdocs.zip)

### Steps to reproduce

1. the zip contains the mkdocs.yml and docs folder
2. render the pages and observe Q2 formula
3. update docs/index.md: goto Q2 section and add space before $$ (the first one) and space after $$ (the second one)
4. render the page and the formula will be rendered correctly

### Before submitting

- [X] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [X] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [X] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [X] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/).

**Comment by squidfunk** [comment]
Thanks for reporting. Did you update to the latest version? Because we just released 9.5.12, which fixes the issue. From the minimal reproduction you shared, it is not apparent which version you're running because you did not use the [info plugin](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/#creating-a-zip-file).

**Comment by fadni** [comment]
I have enabled the info plugin. I have updated to the latest version 9.5.12. The problem still exists.

**Comment by squidfunk** [comment]
Great, thank you! We'll look into it.

**Comment by squidfunk** [comment]
Looping in @facelessuser to rule out that it's related to block processing of Arithmatex.

**Comment by facelessuser** [comment]
Per the documentation: https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/#input-format

> For block forms, the block must start with the appropriate opening for the block type: `$$`, `\[`, and `\begin{}` for the respective search pattern. The block must also end with the proper respective end: `$$`, `\]`, and `\end{}`. A block also must contain no empty lines and should be both preceded and followed by an empty line.

This should be assumed for blocks in general with Python Markdown due to how it works. I won't go into technical reasons why sometimes certain blocks in Python Markdown can work this way and other times they don't, but as a general rule, you are always safe if you have your block by itself, separated from other paragraphs so they don't accidentally get treated as part of the preceding paragraph.

**Comment by squidfunk** [comment]
Muchas gracis @facelessuser, as I suspected. Thus, it's working as intended.

**Comment by fadni** [comment]
Thank you guys
