### ISSUE TITLE
Search results encode `&` as `&amp;`

### ISSUE THREAD

**Issue by kendralockard** [squidfunk/mkdocs-material#8440]
### Bug description

When searching for terms that contain an ampersand (&), MkDocs search results display `&amp;` instead of `&`.

This occurs both on my company documentation site that uses MkDocs, as well as on the official MkDocs documentation site itself (https://squidfunk.github.io/mkdocs-material/).

Example ([here](https://squidfunk.github.io/mkdocs-material/insiders/community-experts-program/?h=%26#your-knowledge-skills)):
<img width="1337" height="940" alt="Image" src="https://github.com/user-attachments/assets/aafc5676-2df4-44c9-a147-12b0b6073763" />

### Related links

Similar issues have been opened and closed in the past, but the problem persists.
- https://github.com/squidfunk/mkdocs-material/issues/2970
- https://github.com/squidfunk/mkdocs-material/issues/2879
- Possibly related: https://github.com/squidfunk/mkdocs-material/issues/271

### Reproduction

I tried but cannot reproduce this bug in a minimal site locally. But, it happens on https://squidfunk.github.io/mkdocs-material/ and our production site.

### Steps to reproduce

1. Open https://squidfunk.github.io/mkdocs-material/ in a browser.
2. Use the search bar to search for a phrase with an ampersand, e.g., `Your knowledge & skills`.
3. All ampersands are shown as `&amp;`.

### Browser

Safari

### Before submitting

- [x] I have read and followed the [bug reporting guidelines](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/).
- [x] I have attached links to [the documentation](https://squidfunk.github.io/mkdocs-material/), and possibly related [issues](https://github.com/squidfunk/mkdocs-material/issues) and [discussions](https://github.com/squidfunk/mkdocs-material/discussions).
- [x] I assure that I have [removed all customizations](https://squidfunk.github.io/mkdocs-material/contributing/reporting-a-bug/#remove-customizations) before submitting this bug report.
- [x] I have attached a __.zip file__ with a [minimal reproduction](https://squidfunk.github.io/mkdocs-material/guides/creating-a-reproduction/) using the [built-in info plugin](https://squidfunk.github.io/mkdocs-material/plugins/info/).

**Comment by squidfunk** [comment]
Thanks for reporting. Fixed in ee678455e.

**Comment by kendralockard** [comment]
Hi @squidfunk , thanks for taking a look at this issue! I went to https://squidfunk.github.io/mkdocs-material/ and am still experiencing the same issue. 

It appears that this is more general than `&` and that other utf8 characters, such as `'` are not being properly escaped either.

Screenshot:

<img width="804" height="730" alt="Image" src="https://github.com/user-attachments/assets/1ee4ea4b-7686-44e2-b8c6-3b7da055ecb9" />

**Comment by squidfunk** [comment]
Thanks for reporting back. I haven't yet merged things through to Insiders, and the changes are not yet released, so that's expected. I've now done the Insiders merge (which is what we build our documentation with), so it works now.

> It appears that this is more general than & and that other utf8 characters, such as ' are not being properly escaped either.

If you can provide a reproduction I can look into this, but without one, I'm not able to help. Please also first check if the issue is gone now in our documentation, and if not, a minimal reproduction is mandatory, as demanded by our bug reporting process.

**Comment by kendralockard** [comment]
Got it, thanks! It appears to be working for me as well now after the Insiders merge.

> If you can provide a reproduction I can look into this, but without one, I'm not able to help. Please also first check if the issue is gone now in our documentation, and if not, a minimal reproduction is mandatory, as demanded by our bug reporting process.

I understand, and I tried to reproduce this locally but was unable to for some reason. But I thought it best to report anyways since it was occurring on both of our production sites. In any case, it appears to be resolved now. Thanks so much!

**Comment by squidfunk** [comment]
Thanks for taking the time to try creating a reproduction. Although bugs might occur on our production site, a clean and focused reproduction helps us to narrow the problem down quickly, as production sites use a combination of settings and plugins which might be causing this. That's why you can help us fix bugs in an instant with a minimal repro. ☺️

Anyway, released as part of [9.6.20](https://squidfunk.github.io/mkdocs-material/changelog/#9.6.20).
